### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [dair-iitd/symnet3#1]
Hi,
could you upload a `requirements.txt` file?

Using `numpy=1.20` I get the following error:

>   File "/symnet3/spektral/utils/misc.py", line 5, in <module>
    def pad_jagged_array(x, target_shape, dtype=np.float):
                                                ^^^^^^^^
  File "/symnet3/env/lib/python3.11/site-packages/numpy/__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

Thanks in advance!

**Comment by GMMDMDIDEMS** [comment]
Upgrading `numpy` to `numpy==1.23.5` does not throw the abovementioned error.  However, upgrading `numpy` to `numpy==1.25.0` produces the same error as above.

**Comment by daman1209arora** [comment]
requirements.txt has been uploaded.

**Comment by GMMDMDIDEMS** [comment]
Did you use `pipreqs` or `pip freeze`? Seems like there are many additional packages listed that aren't used in symnet3.
Using `pipreqs` in the `venv` should provide the correct `requirements.txt`, listing only the required packages.

**Comment by daman1209arora** [comment]
Updated.

**Comment by GMMDMDIDEMS** [comment]
Unfortunately, I still get some dependency issues. Which python version do you use? Are you working on Windows or Linux?

**Comment by daman1209arora** [comment]
I'm using python 3.6.13 on a Linux machine.
