### ISSUE TITLE
ModuleNotFoundError: No module named 'gym.envs.rddl'

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [dair-iitd/symnet3#2]
Hi,
running `python train.py` I get a `ModuleNotFoundError: No module named 'gym.envs.rddl'` error.

I get the following output:

> python train.py
Loaded custom gym
Domain:  navigation
Model dir:  models/
700,701,702,703,704,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899 900,901,902,903,904,905,906,907,908,909
[2023-08-12 15:20:45,186] Making new env: RDDL-navigation700-v1
/Users/.../.../.../symnet3/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False) # resolve()
Traceback (most recent call last):
  File "/Users/.../.../.../symnet3/multi_train/deep_plan/train.py", line 237, in <module>
    train()
  File "/Users/.../.../.../symnet3/multi_train/deep_plan/train.py", line 81, in train
    envs_ = helper.make_envs(instances)
  File "/Users/.../.../.../symnet3/multi_train/deep_plan/helper.py", line 32, in make_envs
    env = gym.make(env_name)
  File "/Users/.../.../.../symnet3/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/Users/.../.../.../symnet3/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/Users/.../.../.../symnet3/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/Users/.../.../.../symnet3/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False) # resolve()
  File "/Users/.../.../.../symnet3/symnet3-env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2517, in load
    return self.resolve()
  File "/Users/.../.../.../symnet3/symnet3-env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2523, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'gym.envs.rddl'

Any ideas?

**Comment by daman1209arora** [comment]
Let me know if this error still persists with the updated requirements.txt file.

**Comment by GMMDMDIDEMS** [comment]
The error persists. I think I missed some setup steps.
The above-mentioned `ModuleNotFoundError: No module named 'gym.envs.rddl'` results from the missing `rddl` folder in the `gym/envs` folder, where probably also the [RDDL.py](https://github.com/dair-iitd/symnet2/blob/main/gym/envs/rddl/RDDL.py) should be located. By copying the [rddl](https://github.com/dair-iitd/symnet2/tree/main/gym/envs/rddl) folder into `gym/envs` I get rid of the error. 

However, solving this issue leads to new issues, e.g. `'/.../.../symnet3/gym/envs/rddl/rddl/parsed/navigation_inst_mdp__700'` cannot be found. This is clear because the `parsed` folder of `symnet2` does not match the `parsed` folder of `symnet3`. I think the cause lies in the problem described above.

Which setup steps are necessary to be able to execute the code?  I found some `.sh` files in the `rddlsim-master` folder. Do I need to execute them?

**Comment by daman1209arora** [comment]
My apologies, this issue was being caused due to the gitignore file which ignored all rddl/ folders. It has been fixed. The rddl/ folder has been uploaded and the gitignore modified. I have also successfully replicated training on a separate machine. It should hopefully work smoothly now.
